# Generated by Django 3.1.2 on 2020-11-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_author'),
        ('items', '0002_auto_20201107_1457'),
    ]

    operations = [
    ]
