# Generated by Django 3.1.2 on 2021-02-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='attachments',
            field=models.FileField(blank=True, default='', upload_to='files/'),
        ),
    ]
