# Generated by Django 3.1.2 on 2020-10-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='items',
        ),
    ]
