# Generated by Django 3.1.2 on 2020-10-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_remove_section_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='date',
        ),
        migrations.RemoveField(
            model_name='section',
            name='time',
        ),
    ]
