# Generated by Django 3.1.2 on 2021-02-07 19:42

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210207_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='attachments',
            field=models.FileField(blank=True, default='', upload_to='attachments/from_comments/', validators=[items.models.file_size]),
        ),
        migrations.AlterField(
            model_name='item',
            name='attachments',
            field=models.FileField(blank=True, default='', upload_to='attachments/from_items/', validators=[items.models.file_size]),
        ),
    ]
