# Generated by Django 3.1.2 on 2021-02-08 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20210207_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='attachments',
            new_name='attachment',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='attachments',
            new_name='attachment',
        ),
    ]
