# Generated by Django 3.1.2 on 2020-11-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrequests',
            name='user_status',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
