# Generated by Django 3.1.2 on 2020-10-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
