# Generated by Django 3.1.2 on 2020-10-24 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0004_auto_20201024_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='admin',
            field=models.ManyToManyField(null=True, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='students',
            field=models.ManyToManyField(null=True, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='teachers',
            field=models.ManyToManyField(null=True, related_name='teachers', to=settings.AUTH_USER_MODEL),
        ),
    ]
