# Generated by Django 3.1.2 on 2020-11-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
