# Generated by Django 3.1.2 on 2020-11-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20201107_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
